"""
Solution grid for the Fisher-KPP problem with the simple Gaussian-bump initial condition of
PDEBench's single-trajectory generator
(`pdebench/data_gen/data_gen_NLE/ReactionDiffusionEq/reaction_diffusion_Hydra.py`, init_mode="react"),
u0(s) = exp(-(s - pi)^2 / (2 (pi/4)^2)) on s in [0, 2 pi) periodic, t in [0, 1] (1024 x 101 grid,
the generator's own).

Companion of `combined_solution_grid.py` (the PDEBench random-IC dataset version) and drawn by
its `make_combined_grid`, so the two figures are laid out identically: one column per reaction
strength rho in {1, 2, 5, 10} at diffusion coefficient nu = 1; rows (a) exact solution, (b) Ours
(posterior predictive mean of the one-pass EP run), (c) our predicted variance (log scale).
Model-side normalized values: rho_norm = 2 rho, nu_norm = 2 nu / (2 pi)^2 (the domain is 2 pi
long, so the diffusion is ~40x milder than the dataset's at the same nu).

The runs use pde/diffusion/mp_pinn_reacdiff_gaussian_run.jl (the dataset
runner's IC-spectrum Kx rule, nt = 2Kt+1, rho-continuation, analytic predictive moments). Exact =
the float64 re-solve of the nominal PDE from the same IC (`reacdiff_reference.gaussian_bump_reference`); the training
data is its t=0 row only. There is one deterministic trajectory per (nu, rho), so the companion
table lists every cell with n = 1 (no spread).

Reads cached artifacts only (`artifacts/mp_pinn_reacdiff_gauss_nu*_rho*.h5`); a missing artifact
raises FileNotFoundError naming the file. Never trains.

Run:  python figures_onepass/diffusion/combined_solution_grid_gaussian.py [--png preview.png]
      leaves combined_solution_grid_gaussian.{pdf,log} and ..._table.tex next to it.
"""

from __future__ import annotations

import sys
from pathlib import Path

import h5py
import numpy as np

FIGURES_DIR = Path(__file__).resolve().parent
REPO_ROOT = FIGURES_DIR.parent.parent
sys.path.insert(0, str(FIGURES_DIR))
sys.path.insert(0, str(REPO_ROOT / "pde" / "diffusion"))

import combined_solution_grid as grid  # noqa: E402
from reacdiff_reference import _fmt, gaussian_bump_reference  # noqa: E402

OUTPUT_PDF = FIGURES_DIR / "combined_solution_grid_gaussian.pdf"
OUTPUT_TABLE = FIGURES_DIR / "combined_solution_grid_gaussian_table.tex"
OUTPUT_LOG = FIGURES_DIR / "combined_solution_grid_gaussian.log"
PNG_PREVIEW: Path | None = None

NUS, RHOS, SHOW_NU = grid.NUS, grid.RHOS, grid.SHOW_NU
ARTIFACTS_DIR = REPO_ROOT / "artifacts"


def cache_path(nu: float, rho: float) -> Path:
    return ARTIFACTS_DIR / f"mp_pinn_reacdiff_gauss_nu{_fmt(nu)}_rho{_fmt(rho)}.h5"


def load_ours(nu: float, rho: float) -> dict:
    path = cache_path(nu, rho)
    if not path.exists():
        raise FileNotFoundError(f"missing artifact {path} (nu={nu}, rho={rho}); generate it with "
                                "pde/diffusion/mp_pinn_reacdiff_gaussian_run.jl")
    u_ref = gaussian_bump_reference(nu, rho)["u_ref"].T  # (n_x, n_t)
    with h5py.File(path, "r") as f:
        pred_u = f["pred_u"][:].T
        r = dict(nu=nu, rho=rho, idx=-1, x=f["x"][:], t=f["t"][:], u_ref=u_ref, pred_u=pred_u,
                 pred_var=f["pred_var"][:].T, Kx=int(f.attrs["Kx"]), epochs=int(f.attrs["epochs"]),
                 rung_epochs=[int(e) for e in np.atleast_1d(f.attrs["rung_epochs"])],
                 train_time_seconds=float(f.attrs["train_time_seconds"]))
    r["rel_l2_ref"] = float(np.linalg.norm(pred_u - u_ref) / np.linalg.norm(u_ref))
    return r


def write_table(results: dict[tuple[float, float], dict], path: Path) -> None:
    """One row per (nu, rho) cell (n = 1 each): the colour-scale extents the drawn panels use
    (drawn cells are those at nu = SHOW_NU), rel-L2 vs the float64 reference, the mean predictive
    variance over the (s, t) grid, and the fitted Kx / EP epochs."""
    lines = [
        r"% Auto-generated by figures_onepass/diffusion/combined_solution_grid_gaussian.py",
        r"% Gaussian-bump IC on [0, 2pi) (PDEBench single-trajectory generator); one run per cell.",
        rf"% The figure draws the nu={SHOW_NU:g} rows. [u_min, u_max]: shared exact/Ours colour scale;",
        r"% [var_min, var_max]: variance log scale; rel-L2 = ||Ours - exact||_2 / ||exact||_2 over the",
        r"% (s, t) grid, exact = float64 re-solve of the nominal PDE; mean sigma^2 over the same grid.",
        r"\begin{tabular}{r r rr rr r r r r}",
        r"\toprule",
        r" & & \multicolumn{2}{c}{$u$ scale} & \multicolumn{2}{c}{$\sigma^2$ scale} & & & & \\",
        r"\cmidrule(lr){3-4}\cmidrule(lr){5-6}",
        r"$\nu$ & $\rho$ & min & max & min & max & rel-$L_2$ & mean $\sigma^2$ & $K_x$ & epochs \\",
        r"\midrule",
    ]
    for nu in NUS:
        for rho in RHOS:
            r = results[(nu, rho)]
            vmin, vmax, var_min, var_max = grid.scale_limits(r)
            mv = float(r["pred_var"].mean())
            lines.append(f"{nu:g} & {rho:g} & {vmin:.3f} & {vmax:.3f} & {var_min:.2e} & {var_max:.2e} & "
                         f"{r['rel_l2_ref']:.4f} & {mv:.2e} & {r['Kx']} & {r['epochs']} \\\\")
            print(f"nu={nu:g} rho={rho:g}: u in [{vmin:.4f}, {vmax:.4f}], var in [{var_min:.3e}, {var_max:.3e}], "
                  f"rel_l2={r['rel_l2_ref']:.5f}, mean var={mv:.3e}, Kx={r['Kx']}, "
                  f"epochs={r['epochs']} (rungs {'+'.join(map(str, r['rung_epochs']))})")
    lines += [r"\bottomrule", r"\end{tabular}"]
    path.write_text("\n".join(lines) + "\n")
    print(f"Saved LaTeX table to {path}")


def main() -> None:
    print("Gaussian-bump IC; no HMC-convergence gate applies (our method only); no run is dropped")
    results = {(nu, rho): load_ours(nu, rho) for nu in NUS for rho in RHOS}
    columns = [results[(SHOW_NU, rho)] for rho in RHOS]
    print(f"figure columns: nu={SHOW_NU:g}, rho in {RHOS}")
    grid.make_combined_grid(columns, OUTPUT_PDF, PNG_PREVIEW)
    write_table(results, OUTPUT_TABLE)


if __name__ == "__main__":
    if "--png" in sys.argv:
        PNG_PREVIEW = Path(sys.argv[sys.argv.index("--png") + 1])
    sys.stdout = grid._Tee(OUTPUT_LOG)
    main()
    sys.stdout.flush()
